# Generated by Django 3.2.4 on 2021-11-19 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('time_limit', models.DurationField(default='00:10:00')),
                ('paper_exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exams')),
                ('student_name', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('question_text', models.TextField()),
                ('marks', models.PositiveIntegerField(default=0)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('answer', models.CharField(choices=[('option1', 'A'), ('option2', 'B'), ('option3', 'C'), ('option4', 'D'), ('', '')], max_length=100)),
                ('question_exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exams')),
                ('question_paper', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='question_paper', to='exam.paper')),
            ],
        ),
        migrations.CreateModel(
            name='ExamTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('paper', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='exam.paper')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.CharField(choices=[('option1', 'A'), ('option2', 'B'), ('option3', 'C'), ('option4', 'D'), ('', '')], max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('mark', models.PositiveIntegerField(default=0)),
                ('question_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Qusetion_related', to='exam.question')),
                ('related_paper', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='related_paper', to='exam.paper')),
                ('student', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_answer_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
