# Generated by Django 3.2.4 on 2021-11-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtime',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='time_limit',
        ),
    ]
