# Generated by Django 3.2.4 on 2021-11-19 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20211119_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtime',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
