# Generated by Django 3.2.4 on 2021-11-19 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_examtime_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtime',
            name='finish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
