# Generated by Django 3.2.4 on 2021-11-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20211119_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_finished',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
